name: dreem

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - conda-forge::opencv <4.9.0
  - pytorch
  - cpuonly
  - torchvision
  - lightning
  - imageio
  - av
  - ffmpeg
  - albumentations
  - matplotlib
  - pip
  - pip:
    - matplotlib
    - sleap-io
    - "--editable=.[dev]"
    - imageio[ffmpeg]
    - hydra-core
    - motmetrics
    - seaborn
    - wandb
    - timm
