model:
  ckpt_path: null
  encoder_cfg: 
      model_name: "resnet18"
      in_chans: 3
      backend: "timm"
      pretrained: false
  d_model: 128
  nhead: 1
  num_encoder_layers: 1
  num_decoder_layers: 1
  dropout: 0.1
  activation: "relu"
  return_intermediate_dec: True
  norm: False
  num_layers_attn_head: 1
  dropout_attn_head: 0.1
  embedding_meta:
    pos:
        mode: "learned"
        emb_num: 16
        over_boxes: true
        normalize: true
    temp:
        mode: "learned"
        emb_num: 16
  return_embedding: False
  decoder_self_attn: True

loss:
  epsilon:  0.0001
  asso_weight: 10.0

optimizer:
  lr: 0.0001
  weight_decay: 0

scheduler:
  factor: 0.5
  patience: 5
  threshold: 0.001

dataset:
  train_dataset:
    dir: 
        path: "/Volumes/talmodata/datasets/mot/animal/sleap/btc/large_run/als/train"
        labels_suffix: ".slp"
        vid_suffix: ".mp4"
    clip_length: 32
    crop_size: 64
    padding: 0
    anchors: "centroid"
    augmentations:
      Rotate:
        limit: 45
        p: 0.3
      GaussianBlur:
        blur_limit: [3,7]
        sigma_limit: 0
        p: 0.3
      RandomBrightnessContrast:
        brightness_limit: 0.1
        contrast_limit: 0.3
        p: 0.3
      MotionBlur:
        blur_limit: [3,7]
        p: 0.3
      # NodeDropout:
      #   p: 0.3
      #   n: 5
      # InstanceDropout:
      #   p: 0.3
      #   n: 1
    n_chunks: 200
    handle_missing: "centroid"
    seed: 42
    
  val_dataset:
      dir: 
        path: "/Volumes/talmodata/datasets/mot/animal/sleap/btc/large_run/als/val"
        labels_suffix: ".slp"
        vid_suffix: ".mp4"
      crop_size: 64
      padding: 0
      anchors: "centroid"
      n_chunks: 50
      handle_missing: "centroid"
      seed: 42
      
  test_dataset:
      slp_files: []
      video_files: []

dataloader:
  train_dataloader:
    num_workers: 0
  val_dataloader:
    num_workers: 0
  test_dataloader: 
    num_workers: 0

checkpointing:
  save_top_k: -1

trainer:
  max_epochs: 2
  min_epochs: -1
  # limit_train_batches: 0.001
  # limit_test_batches: 1.0
  # limit_val_batches: 0.004
  profiler: "advanced"
  

logging:
  project: "dreem"
  # group: "mice-btc"
  # entity: "aaprasad"
  # name: "mice-with-embeddings-small-run-main"
  # notes: ""
  logger_type: null #"WandbLogger"

tracker:
  window_size: 8
  overlap_thresh: 0.1
  mult_thresh: true
  decay_time: null
  iou: null
  max_center_dist: null
  
runner:
    persistent_tracking:
        train: false
        val: false
        test: false
    metrics:
        train: []

# view_batch:
#   enable: True
#   num_frames: 5
#   no_train: True
