version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  empty:
    class: logging.NullHandler
loggers:
  dreem:
    level: INFO
    propagate: no
  dreem.datasets:
    level: INFO
    propagate: yes
    parent: [loggers.dreem]
  dreem.inference:
    level: INFO
    propagate: yes
    parent: [loggers.dreem]
  dreem.io:
    level: INFO
    propagate: yes
    parent: [loggers.dreem]
  dreem.models:
    level: INFO
    propagate: yes
    parent: [loggers.dreem]
  dreem.training:
    level: INFO
    propagate: yes
    parent: [loggers.dreem]
root:
  level: [INFO]
  handlers: [empty]

  
