model:
  activation: relu
  ckpt_path: null
  d_model: 128
  decoder_self_attn: true
  dropout: 0.1
  dropout_attn_head: 0.1
  embedding_meta:
    embedding_agg_method: average
    pos:
      emb_num: 16
      mode: learned
      normalize: true
      over_boxes: true
    temp:
      emb_num: 16
      mode: learned
  encoder_cfg:
    backend: timm
    in_chans: 3
    model_name: resnet18
    pretrained: false
  nhead: 1
  norm: false
  num_decoder_layers: 1
  num_encoder_layers: 1
  num_layers_attn_head: 1
  return_embedding: false
  return_intermediate_dec: true

loss:
  neg_unmatched: false
  epsilon: 1e-4
  asso_weight: 1.0

optimizer:
  name: "Adam"
  lr: 0.0001
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0.01

#currently assumes reduce lr on plateau
scheduler:
  name: "ReduceLROnPlateau"
  mode: "min"
  factor: 0.5
  patience: 5
  threshold: 0.001
  threshold_mode: "rel"

runner:
  metrics:
      train: ['num_switches']
      val: ['num_switches']
      test: ['num_switches']
  persistent_tracking:
      train: false
      val: true
      test: true
      
dataset:
  train_dataset:
    anchors: "centroid"
    augmentations:
      GaussianBlur:
        blur_limit:
        - 3
        - 7
        p: 0.2
        sigma_limit: 0
      MotionBlur:
        blur_limit:
        - 3
        - 7
        p: 0.2
      RandomBrightnessContrast:
        brightness_limit: 0.1
        contrast_limit: 0.3
        p: 0.3
      Rotate:
        limit: 45
        p: 0.3
    slp_files: ['./data/two_flies.slp']
    video_files: ['./data/two_flies.mp4']
    clip_length: 32
    chunk: True
    padding: 0
    crop_size: 128

  val_dataset:
    anchors: "centroid"
    slp_files: ['./data/two_flies.slp']
    video_files: ['./data/two_flies.mp4']
    padding: 0
    crop_size: 128 
    chunk: True
    clip_length: 32

  test_dataset:
    slp_files: []
    video_files: []
    padding: 0
    crop_size: 128 
    chunk: True
    clip_length: 32

dataloader:
  train_dataloader:
    shuffle: true
    num_workers: 0
  val_dataloader:
    shuffle: false
    num_workers: 0
  test_dataloader: 
    shuffle: false
    num_workers: 0

logging:
  logger_type: null
  name: "example_train"

early_stopping:
  monitor: "val_loss"
  min_delta: 0.1
  patience: 10
  mode: "min"
  check_finite: true
  stopping_threshold: 1e-8
  divergence_threshold: 30

checkpointing:
  monitor: ["val_loss"]
  verbose: true
  save_last: true
  dirpath: null
  auto_insert_metric_name: true
  every_n_epochs: 1
  save_top_k: 1

trainer:
  check_val_every_n_epoch: 1
  enable_checkpointing: true
  gradient_clip_val: null
  limit_train_batches: 1.0
  limit_test_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 1
  max_epochs: 5
  min_epochs: 1
