# Windows CI - Manual trigger only
name: CI Windows

on:
  workflow_dispatch:

defaults:
  # This is needed for running steps within conda environments.
  run:
    shell: bash -l {0}

jobs:
  # Tests with pytest on Windows
  tests-windows:
    name: Tests (Windows, Python 3.12)
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Micromamba
        # https://github.com/mamba-org/setup-micromamba
        # Note: Set channel-priority in .condarc if needed
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment_cpu.yml
          cache-environment: true
          cache-environment-key: environment-${{ hashFiles('environment_cpu.yml') }}-${{ hashFiles('pyproject.toml') }}
          init-shell: >-
            bash
            powershell
          post-cleanup: all

      - name: Print environment info
        shell: bash -l {0}
        run: |
          which python
          micromamba info
          micromamba list
          pip freeze

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest